TicketOnline/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TicketOnline.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Ứng dụng đặt vé xe trực tuyến";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TicketOnline/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketOnline.Models;

namespace TicketOnline.Controllers
{
    public class InformationController : Controller
    {
        // GET: Information
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetInformation(PassengerViewModel model)
        {
            CoachViewModel resuftCoach = new CoachViewModel();
            if (model != null && !String.IsNullOrEmpty(model.FirstName))
            {
                PassengerSessionModel.FromSession(this.Session).getPassenger(model);
                TicketDataContext dc = new TicketDataContext();
                List<Coach> coaches = new List<Coach>();
                if(model.Hour == null || String.IsNullOrEmpty(model.Hour))
                {
                    coaches = dc.Coaches.Where(q => q.StartDate == DateTime.ParseExact(model.StartDate, "dd/MM/yyyy", null)).ToList();
                }
                else
                {
                    coaches = dc.Coaches.Where(q => q.StartDate == DateTime.ParseExact(model.StartDate, "dd/MM/yyyy", null) && q.StartHour == model.Hour).ToList();
                }
                
                foreach (Coach coach in coaches)
                {
                    resuftCoach.Name = coach.Name;
                    resuftCoach.NumberSeat = coach.NumberSeat;
                    resuftCoach.Router = coach.Router;
                    resuftCoach.StartDate = coach.StartDate;
                    resuftCoach.StartHour = coach.StartHour;
                    resuftCoach.Id = coach.Id;

                    for (int i = 0; i < resuftCoach.NumberSeat; i++)
                    {
                        TicketVewModel ticket = new TicketVewModel();
                        ticket.SeatId = i;
                        resuftCoach.Tickets.Add(ticket);
                    }

                    List<Ticket> tickets = dc.Tickets.Where(q => q.CoachId == resuftCoach.Id).ToList();
                    if (tickets.Count > 0)
                    {
                        foreach (Ticket ticket in tickets)
                        {
                            resuftCoach.Tickets[ticket.SeatId].Status = ticket.Status;
                        }
                    }
                    break;
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            return View(resuftCoach);
        }
    }
}

TicketOnline/Views/Home/About.cshtml
@{
    ViewBag.Title = "Thông tin";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Họ và Tên: Lê Minh Thành</p>
<a href="mailto:leminhthanh0612@gmail.com" >Email: leminhthanh0612@gmail.com</a>

TicketOnline/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TicketOnline/Views/Home/Index.cshtml
@model TicketOnline.Models.PassengerViewModel
@{
    ViewBag.Title = "Trang Chủ";
}

<!--<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
-->

<div class="row">

    <!--Un-Use code-->
    <!--<div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>-->
    @using (Html.BeginForm("GetInformation", "Information", FormMethod.Post, new { @class = "form-horizontal", role = "form", @name="passenger",@id= "passenger" }))
    {



        @*@Html.ValidationSummary(true)*@
        @*@Html.AntiForgeryToken()*@
        <h4>Thông tin đăng ký - hành khách</h4>
        <hr />
        @*@Html.ValidationSummary("", new { @class = "text-danger" })*@

        <div class="form-group">
            <label for="Hour" class="col-md-2 control-label">Tên</label>
            <div class="col-md-10">
                <input type="text" name="FirstName" id="FirstName" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label for="LastName" class="col-md-2 control-label">Họ</label>
            <div class="col-md-10">
                <input type="text" name="LastName" id="LastName" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label for="Phone" class="col-md-2 control-label">Số điện thoại</label>
            <div class="col-md-10">
                <input type="number" name="Phone" id="Phone" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label for="Email" class="col-md-2 control-label">Email</label>
            <div class="col-md-10">
                <input type="text" name="Email" id="Email" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label for="StartDate" class="col-md-2 control-label">Ngày khởi hành</label>
            <div class="col-md-10">
                <input type="text" name="StartDate" id="StartDate" class="form-control date-picker" />
            </div>
        </div>
        <div class="form-group">
            <label for="Hour" class="col-md-2 control-label">Giờ khởi hành</label>
            <div class="col-md-10">
                <select id="Hour" class="form-control" name="Hour">
                    <option value="8:00">8:00</option>
                    <option value="13:30">13:30</option>
                    <option value="20:00">20:00</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Tiếp tục" />
            </div>
        </div>
        }

</div>